name: ci
on: [push]
jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.21"
      - name: lint
        run: make lint
      - name: test
        run: make test
